# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fogli}
  s.version = "0.2.0.dev"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mitchell Hashimoto"]
  s.date = %q{2010-06-09}
  s.description = %q{An efficient, simple, and intuitive Facebook Open Graph library.}
  s.email = %q{mitchell.hashimoto@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "examples/README.md",
     "examples/me/README.md",
     "examples/me/me.rb",
     "fogli.gemspec",
     "lib/fogli.rb",
     "lib/fogli/album.rb",
     "lib/fogli/categorized_object.rb",
     "lib/fogli/comment.rb",
     "lib/fogli/event.rb",
     "lib/fogli/exception.rb",
     "lib/fogli/facebook_graph.rb",
     "lib/fogli/facebook_object.rb",
     "lib/fogli/facebook_object/connection_proxy.rb",
     "lib/fogli/facebook_object/connection_scope.rb",
     "lib/fogli/facebook_object/connections.rb",
     "lib/fogli/facebook_object/properties.rb",
     "lib/fogli/facebook_object/scope_methods.rb",
     "lib/fogli/group.rb",
     "lib/fogli/link.rb",
     "lib/fogli/named_object.rb",
     "lib/fogli/note.rb",
     "lib/fogli/oauth.rb",
     "lib/fogli/page.rb",
     "lib/fogli/photo.rb",
     "lib/fogli/post.rb",
     "lib/fogli/status.rb",
     "lib/fogli/user.rb",
     "lib/fogli/util/module_attributes.rb",
     "lib/fogli/util/options.rb",
     "lib/fogli/video.rb",
     "test/fogli/facebook_graph_test.rb",
     "test/fogli/facebook_object/connection_proxy_test.rb",
     "test/fogli/facebook_object/connection_scope_test.rb",
     "test/fogli/facebook_object/connections_test.rb",
     "test/fogli/facebook_object/properties_test.rb",
     "test/fogli/facebook_object/scope_methods_test.rb",
     "test/fogli/facebook_object_test.rb",
     "test/fogli/oauth_test.rb",
     "test/fogli/post_test.rb",
     "test/fogli/user_test.rb",
     "test/fogli/util/options_test.rb",
     "test/fogli_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/mitchellh/fogli}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{An efficient, simple, and intuitive Facebook Open Graph library.}
  s.test_files = [
    "test/fogli/facebook_object/connection_proxy_test.rb",
     "test/fogli/facebook_object/scope_methods_test.rb",
     "test/fogli/facebook_object/connections_test.rb",
     "test/fogli/facebook_object/connection_scope_test.rb",
     "test/fogli/facebook_object/properties_test.rb",
     "test/fogli/user_test.rb",
     "test/fogli/oauth_test.rb",
     "test/fogli/post_test.rb",
     "test/fogli/facebook_graph_test.rb",
     "test/fogli/util/options_test.rb",
     "test/fogli/facebook_object_test.rb",
     "test/test_helper.rb",
     "test/fogli_test.rb",
     "examples/me/me.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.5.1"])
      s.add_runtime_dependency(%q<json_pure>, ["~> 1.2.0"])
    else
      s.add_dependency(%q<rest-client>, ["~> 1.5.1"])
      s.add_dependency(%q<json_pure>, ["~> 1.2.0"])
    end
  else
    s.add_dependency(%q<rest-client>, ["~> 1.5.1"])
    s.add_dependency(%q<json_pure>, ["~> 1.2.0"])
  end
end

